### ISSUE TITLE
Firefox issue with sampleRate?

### ISSUE THREAD

**Issue by StefanoCecere** [GoogleChromeLabs/audioworklet-polyfill#1]
any idea why Firefox doesn't play the sine wave (but the noise) in https://audio-dsp-playground-polyfilled.surge.sh/?

i discover that the problem is this:

`time += 1 / sampleRate;`

if i change it in
`
time += 1 / 44000;`

IT WORKS! maybe the sampleRate var isn't well configured in FF?

**Comment by developit** [comment]
Hi @StefanoCecere! Thanks for the debugging - it looks like I never redeployed that demo after fixing sampleRate :) I'll update it today.

**Comment by developit** [comment]
Deployed.
