### ISSUE TITLE
Crash after creating AudioWorkletNode

### ISSUE THREAD

**Issue by warpdesign** [GoogleChromeLabs/audioworklet-polyfill#10]
The following code crashes when ran in Firefox with audioworklet-polyfill:

```js
this.context.audioWorklet.addModule('js/mod-processor.js').then(() => {
            this.workletNode = new AudioWorkletNode(this.context, 'mod-processor');
            this.workletNode.port.onmessage = this.handleMessage.bind(this);
            // ...
}
```

Because this.workletNode.port isn't defined.

Looking at the source code of the polyfill, it seems `new AudioWorkletNode` returns the `ScriptProcessorNode` instead of the `AudioWorkletNode` (which has the `port` correctly set).

https://github.com/GoogleChromeLabs/audioworklet-polyfill/blob/4382ddc7d2ff1f86b74797cfddba8ff168e26659/src/index.js#L22-L48

Native AudioWorkletNode correctly returns the `AudioWorkletNode` object which has the `port` property set so the code works as expected here.

**Comment by developit** [comment]
Ah - whoops, this is an issue with the release that went out 2 days ago. Good catch!
