### ISSUE TITLE
TypeError: context.audioWorklet is undefined   in Firefox

### ISSUE THREAD

**Issue by iooops** [GoogleChromeLabs/audioworklet-polyfill#17]

**Comment by JohnWeisz** [comment]
I'm wondering why this was closed, I'm getting the same issue on Chrome Android 73. It seems `AudioWorkletNode` _is_ defined, but it seems like the AudioWorklet is an incomplete implementation, and `AudioContext.prototype.audioWorklet` is not defined. Adding `"audioWorklet" in AudioContext.prototype` seems to detect it correctly.
