### ISSUE TITLE
My code doesn't work in Firefox

### ISSUE THREAD

**Issue by aatishb** [GoogleChromeLabs/audioworklet-polyfill#5]
I have a demo of a sine wave, live [here](https://indigo-ptarmigan.glitch.me/) and code [here](https://glitch.com/edit/#!/indigo-ptarmigan). It produces sound in Chrome and shows the spectrum. In Firefox I get no sound or spectrum, and no error in the console.

It seems like the issue is the code after

`
let sound = new AudioWorkletNode(audio, 'audio-processor');
`

is not being executed. Wonder if anyone could offer any insight. Thanks.

**Comment by aatishb** [comment]
Wonder if anyone can help with this. It works fine in Chrome, but doesn't work in Firefox or Safari with no error provided.

**Comment by developit** [comment]
Your demo works with [1.1.0](https://github.com/GoogleChromeLabs/audioworklet-polyfill/releases/tag/1.1.0) now!

I had to remix your glitch to request audio playback permission, but that's unrelated to the AudioWorklet polyfill:
https://glitch.com/edit/#!/resolute-peak

**Comment by aatishb** [comment]
This is great, thanks! I noticed that the messageport feature doesn't seem to be supported. Are there any plans for adding this in future? Thanks.
