### ISSUE TITLE
'AudioWorkletProcessor.port' is undefined

### ISSUE THREAD

**Issue by JohnWeisz** [GoogleChromeLabs/audioworklet-polyfill#8]
For example, doing this in:

```
class MyWorkletProcessor extends AudioWorkletProcessor
{
    constructor()
    {
        super();
        this.port.onmessage = (e) => ...
    }
}
```

Will result in an error, because `this.port` is `undefined`.

(I hate to be picky, but did anyone actually _test_ this project? Really doesn't seem so, virtually everything is broken in it...)

**Comment by developit** [comment]
The port is assigned, it's just done after construction. I'll move it into the constructor so that your example works.
